version: '3.1'

services:
  app:
    build: .
    restart: always
    image: app
    depends_on:
      - dbase
    ports:
        [5000:5000]
    env_file: .env
    environment:
      - SQLALCHEMY_DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
  dbase:
    image: postgres:14
    restart: always
    ports:
        [5432]
    env_file: .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
